"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://eha.mywikis.wiki/wiki/Main_Page
  name = eha

Install this in the following folder
Users\00006605\AppData\Local\Programs\Python\Python313\Lib\families\
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'eha'
    langs = {
        'en': 'eha.mywikis.wiki',
    }

    def scriptpath(self, code):
        return {
            'en': '/w139',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
